SELECT F.FLAVOR
FROM FIRST_HALF F 
JOIN (SELECT FLAVOR ,SUM(TOTAL_ORDER) JULY_ORDER
        FROM JULY
        GROUP BY FLAVOR) J
ON F.FLAVOR = J.FLAVOR
ORDER BY TOTAL_ORDER + JULY_ORDER DESC 
LIMIT 3;