SELECT ID, FISH_NAME, MAX_LENGTH AS LENGTH
FROM FISH_INFO
JOIN FISH_NAME_INFO
ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
JOIN (SELECT FISH_TYPE, MAX(LENGTH) MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE) A
ON A.FISH_TYPE = FISH_INFO.FISH_TYPE
WHERE FISH_INFO.LENGTH = A.MAX_LENGTH