WITH A AS(SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
                               ,CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= "90" THEN "90일 이상"
                                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= "30" THEN "30일 이상"
                                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= "7" THEN "7일 이상"
                            END DURATION_TYPE 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT HISTORY_ID, ROUND(DAILY_FEE * DURATION * (1 - (IFNULL(DISCOUNT_RATE, 0) / 100)), 0) FEE
FROM A 
JOIN CAR_RENTAL_COMPANY_CAR C
ON A.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON A.DURATION_TYPE = P.DURATION_TYPE AND C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE = "트럭"
ORDER BY FEE DESC ,HISTORY_ID DESC ;